//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DentalCare.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblBillService
    {
        public int BillServiceId { get; set; }
        public int BillId { get; set; }
        public int ServiceId { get; set; }
        public bool IsActive { get; set; }
        public bool IsDeleted { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string CreatedBy { get; set; }
        public string ModifiedBy { get; set; }
    
        public virtual tblService tblService { get; set; }
        public virtual tblBill tblBill { get; set; }
    }
}
